steps:
  # Single step to install and run dbt
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install dbt-bigquery
        dbt deps --profiles-dir .
        dbt run --target prod --profiles-dir .

timeout: '1800s'
options:
  logging: CLOUD_LOGGING_ONLY