dbt_opsfleet:
  outputs:
    dev:  # Your local development (unchanged)
      schema: analytics
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/roeecohen/Documents/Coding/OpsfleetBigQuery/gcptutorial-340819-e8abc1ab4858.json
      location: US
      method: service-account
      priority: interactive
      project: gcptutorial-340819
      threads: 4
      type: bigquery
    
    prod:  # For Cloud Build
      schema: analytics
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: gcptutorial-340819
      threads: 4
      type: bigquery
      
  target: dev